name: qx

on:

  schedule:
    - cron: '30 5 * * 1,3'
  push:
    branches: [ "main" ]
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installation depends
        run: |
          sudo apt-get update
          sudo apt-get -y install curl

      - name: checkout actions
        uses: actions/checkout@v3

      - name: generate clean-list
        run: sh ./script.sh

      - name: get clash rules from LM-Firefly and Loyalsoldier
        run: |
          mkdir output/rules && cd output/rules
          wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Telegram/Telegram.list
          wget https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Netflix/Netflix.list

      - name: get ios_rule_script
        uses: actions/checkout@v3
        with:
          repository: blackmatrix7/ios_rule_script
          path: ios_rule_script 

      - name: cp_clash_rule
        run: mv ios_rule_script/rule/QuantumultX output/rules/ 

         
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash
        
      - name: Release and upload assets
        uses: softprops/action-gh-release@v0.1.6
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          draft: false
          prerelease: false
          files: |
            ./output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Git push assets to "release" branch
        run: |
          cd output || exit 1
          git init
          git config --local user.name "dsmmyq"
          git config --local user.email "dsmmyq@gmail.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release
